---
  - block:

    #  - name: Install middleman plugin
    #    shell: luarocks install middleman

    - name: ensure git
      shell: apk update && apk add git

    - name: Clone middleman 
      shell: "cd {{kong_plugins_path}} && git clone https://github.com/pantsel/kong-middleman-plugin middleman"

    - name: Build middleman
      shell: "cd {{kong_plugins_path}}/middleman && luarocks make *.rockspec"

    - name: remove git
      shell: apk del git

    when: option_plugin_middleman
