---
version: '3.1'
services:
  nginx:
    image: sa-kong-container-kong:latest
    ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 8444:8444
 
#    command: ['/usr/bin/dumb-init', 'nginx', '-c', '/etc/nginx/nginx.conf']
#    volumes:
#    - "${PWD}/standalone-fallback/files/conf/demo.conf:/etc/nginx/sites-enabled/demo.conf"
#    - "${PWD}/standalone-fallback/files:/www"
